### ISSUE TITLE
Click TM suggestion to open in new tab

### ISSUE THREAD

**Issue by sujato** [suttacentral/bilara#1]
When TM suggestions are shown, sometimes you want to change to translation in the suggested segment. I want to be able to click it and have it open that segment in context in a new tab.

Currently if you click it the segment is added to the current translation. So there needs to be a distinct UI for opening in a new segment. Perhaps a button on the right side of div.row.translation. Currently this space is occupied by the "match quality" indicator. But this more accurately refers to the match of the *root text*, so should be place on the left of div.row.

Something roughly like this:

![Screenshot from 2019-07-22 09-52-38](https://user-images.githubusercontent.com/6112010/61598892-96e8ed80-ac66-11e9-97ec-6b37ac800105.png)

[match.zip](https://github.com/suttacentral/bilara/files/3415203/match.zip)

**Comment by blake-sc** [comment]
So to be clear, you want to be able to open the origin text of the suggestion, focused at the segment?

We should bear in mind that it's possible there will be multiple origins for the suggestion.

**Comment by sujato** [comment]
Actually, that's a great idea. We'd be better off handling this as a find/replace function. 

You should be able to easily:

- search a suggested string
- search a root text
- search a translation

Then replace all or per instance as usual in the find/replace UI.

Tell you what, I'll close this issue and add these details to 

https://github.com/suttacentral/bilara/issues/11
