### ISSUE TITLE
Bilara broken?

### ISSUE THREAD

**Issue by 153** [suttacentral/bilara#156]
Hi, I'm a first time user of Bilara and just logged in.  
There is a hung "Loading" message and a heap of error messages.   
Using latest version Google Chrome on Windows 11, but this *also* occurs in latest version Firefox.

Is this happening for anyone else? How can I fix it? 

I also checked the JS console and see an HTTP 500 "Internal Server Error" from the path `https://bilara.suttacentral.net/api/nav/` was returned, which may have something to do with this problem. 

![image](https://github.com/suttacentral/bilara/assets/1646449/e3db67d2-ac5e-4e9f-893b-0cc62090c148)

**Comment by sujato** [comment]
Thanks, we're aware of this issue and investigating it. It might have something to do with [recent cloudflare outages](https://www.cloudflarestatus.com/incidents/hm7491k53ppg), or else a problem with billing at cloudflare. In any case, hold on for a little while and we'll resolve it.

**Comment by ihongda** [comment]
Bilara should be able to be used normally now, please try again 🙏🏼

**Comment by 153** [comment]
> Bilara should be able to be used normally now, please try again 🙏🏼

Looks good now 🙏🏼

**Comment by 153** [comment]
🙏🏼 Looks good now @ihongda
