### ISSUE TITLE
Clicking on TM prompt saves string

### ISSUE THREAD

**Issue by sujato** [suttacentral/bilara#19]
When accepting a TM prompt the accepted string seems to be persistent. I am not sure if it is actually committed or not, but if you click away and then come back, the accepted string is still there.

This is an anti-pattern, as we should only commit strings by <kbd>Enter</kbd>. Failure to do so creates an ambiguous state. The string should be discraded when you navigate away.

**Strings must only but committed by <kbd>Enter</kbd>. If a TM prompt is accepted, but not committed by <kbd>Enter</kbd>, when one navigates away the string is discarded.**

**Comment by blake-sc** [comment]
State is now committed only by <kbd>Enter</kbd>. Furthermore there is an indicator next to an entry either warning that it is uncommitted, or acknowledging that it has been committed.
