### ISSUE TITLE
Regenerate bi-vb-pd2-8 from HTML

### ISSUE THREAD

**Issue by sujato** [suttacentral/bilara#37]
Due to changes made by Brahmali, and an undebaked source, the files for bi-pd have got in a tangle.

Here is the corrected source file, please regenerate all files from this.

[pli-tv-bi-vb-pd2-8.zip](https://github.com/suttacentral/bilara/files/3710592/pli-tv-bi-vb-pd2-8.zip)

Note that **the segment numbers are correct already**. Please don't change them.

**Comment by blake-sc** [comment]
Done, if the results look good can close

**Comment by sujato** [comment]
Looks good
