### ISSUE TITLE
Accurately display committed state of translation strings

### ISSUE THREAD

**Issue by blake-sc** [suttacentral/bilara#42]
There are three possible strings which can pertain to a given segment:

1. The *working string*, that is the string which is actually in the text field.
2. The *submitted string*, that is when <kbd>Enter</kbd> has been pressed the working string becomes the *submitted string*.
3. The *committed string*, this is, to the best knowledge of the client, the string which is actually in the repository.

It is desirable to show an indication of what state a segment is in, and we can a variety of scenarios:

1. The working string is the identical to the committed string, we can consider this the untouched or reverted state.
2. The working string is different than the submitted string (which could be null) and the user's cursor is still in the text box. `working_string != submitted_string && selected`, *this need not display anything*.
3. Same as above, but the user has deselected the text box, `working string != submitted_string && !selected` *this should display a warning indicator*.
4. The working string is the same as the submitted string, but the submitted string is different than the committed string, `working_string == submitted_string && submitted_string != committed_string`, we can consider this the "pending" state.
5. The working string, submitted string and committed string are all identical, `working_string == submitted_string && submitted_string == committed_string`, we can consider this the  "confirmed" state.

**Comment by sujato** [comment]
So it seems as if the confusions so far revolve around the “pending” state, which has no indicator. 

May I ask: under what conditions does the pending become confirmed? Does this require manual intervention, or is it normally just a matter of waiting till the system does it.

Perhaps we should have a “conflict” indicator for cases where a pending string has been rejected due to merge conflicts?

**Comment by sujato** [comment]
seems fine now
