### ISSUE TITLE
Make Bilara aware of new bilara-data documents

### ISSUE THREAD

**Issue by firepick1** [suttacentral/bilara#48]
@Blake, this suggests to me that Bilara is only checking for new suttas on initialization rather than periodically. We are updating bilara-data via pull request from a fork of bilara-data. If this is the case, then I believe we will need one of the following:

* Bilara scheduled polling of bilara-data
* User-initiated polling of bilara-data

**Comment by blake-sc** [comment]
Bilara uses a webhook to be notified of updates to the data repository. So the code which responds to the webhook has to be updated to react correctly to files being added.

**Comment by sujato** [comment]
If I understand this correctly, the issue is resolved. Bilara does in fact update when new documents are added.
