### ISSUE TITLE
Bilara TM is stale and does not update 

### ISSUE THREAD

**Issue by sujato** [suttacentral/bilara#5]
The TM prompts in Bilara are old, frequently suggesting segments that have long been replaced (hint, check if capital letters are used for line initials in thag/thig; the old style capitalizes each linke, new style only capitalizes the first line of the verse.)

Moreover, the TM does not update as translations are made.

**TM should always reflect the latest state of bilara-data.**

**Comment by blake-sc** [comment]
It's up to date now. Still need to verify that it reliably updates as translations are made.

**Comment by sujato** [comment]
Can confirm the TM has new translations. However it still does not seem to update as translations are changed.

**Comment by sujato** [comment]
Currently it seems to usually update TM prompts after refresh only. Occasionally the prompts reflect a new change, but normally not.
