### ISSUE TITLE
Don’t use contentEditable

### ISSUE THREAD

**Issue by sujato** [suttacentral/bilara#7]
Bilara uses contentEditable for text input, but this is specifically a browser API for rich text. There are lots of articles on the web explaining in great detail why it sucks! Since we definitely do *not* want rich text, we should not use it.

I already encountered problems with this, if pasting formatted text into the field it will keep the formatting.

![Screenshot from 2019-07-22 10-21-49](https://user-images.githubusercontent.com/6112010/61617019-3cbf4b00-acad-11e9-9413-72c4b42a21e0.png)

**Use `<textarea>`, which only submits plain text.**

One limitation of `<textarea>` is that it displays a fixed number of rows (browser default is 2). We need it to display exactly the amount of rows as the text takes up. This is not an optional extra: you need to be able to read the text by scanning it, not scrolling or grabbing the handles of text areas and dragging them. Unfortunately it seems there is no HTML or CSS for this. There are various JS solutions, here is what seems like a very cool one:

https://colloq.io/blog/auto-resizing-textareas-with-ecmascript-6 

 And some other examples:

https://vaadin.com/components/vaadin-text-field/html-examples/text-area-demos
https://stackoverflow.com/questions/454202/creating-a-textarea-with-auto-resize
https://codepen.io/vsync/pen/frudD
http://www.jacklmoore.com/autosize/

**Comment by blake-sc** [comment]
It's possible to use `contenteditable="plaintext-only"` or in CSS `-webkit-user-modify: read-write-plaintext-only;` which does exactly what you'd expect: it disables any ability to add markup via control keys, and paste inserts plain text.

I find it attractive that contenteditable is a perfectly ordinary element without any tricks needed to undo the user-agent stylesheet and without the javascript tricks needed to make it act like an ordinary element.

Anyway for the moment I've implemented "plaintext-only", see if it's satisfactory.

**Comment by sujato** [comment]
Okay, it works, let's see how it goes.
