### ISSUE TITLE
Rename `sutta` to `text` in bilara-data

### ISSUE THREAD

**Issue by sujato** [suttacentral/bilara#77]
In bilara-data, we use a folder named `sutta` to distinguish from eg. `name` or `blurb`. However this invites confusion, as it includes Suttas, Vinaya, and Abhidhamma. Better to rename it `text`.

**Comment by sabbamitta** [comment]
As far as I can see, the only folder called `sutta` that contains anything other than actual suttas is the folder of the comm-team; it is called `sutta` and has only comm. All other `sutta` folders, as far as I can see, contain only suttas. Ajahn Brahmali's folder is called `vinaya`.

**Comment by sujato** [comment]
You are quite right, how embarrassing, I wil close this issuse

**Comment by sabbamitta** [comment]
No worries! :smiley:
