### ISSUE TITLE
Eliminate match quality data

### ISSUE THREAD

**Issue by sujato** [suttacentral/bilara#9]
It's always cute to add data to interfaces, but it isn't always useful. I'm struggling to think of a genuine use for match quality. When considering TM suggestions the *percentage* correct is irrelavent: I scan the suggestions, if one seems good to accept, I do so, otherwise I start writing. Match quality is just noise.

Given that is has a cost on code and UI complexity, let us simply remove it, we can add it back if it is needed.

**Remove match quality data from TM suggestions.**

**Comment by blake-sc** [comment]
The match quality is used internally to decide which matches to actually show and how to rank them. It can be useful to know it for debugging purposes but I can always remove it from the UI.

**Comment by sujato** [comment]
Let's try just remove from the UI for now, even just throw a `display:none` on the CSS and see whether it is missed.
